// src/pages/SignUp/SignUp.tsx
import React, {useState} from "react";
import Home from "../../components/Home/Home.tsx";
import {Button, Input} from "@material-tailwind/react";
import {VisibilityOffOutlined, VisibilityOutlined} from "@mui/icons-material";
import {signUp} from "./signUp.ts";
import {AlertNotif, useAlertNotif} from "../../components/Alert.tsx";
import {Link, useNavigate} from "react-router-dom";
import {replacePersianNumbers} from "../../utils/replacePersianNumbers";
import {nationCodeValidator} from "../../utils/nationalCodeValidator";

function SignUp() {
    const [formData, setFormData] = useState({
        first_name: "",
        phone_number: "",
        email: "",
        username: "",
        national_code: "",
        password: "",
        password2: "",
        showPassword: false,
        role: "customer"
    });

    const [errors, setErrors] = useState({
        first_name: "",
        phone_number: "",
        email: "",
        username: "",
        national_code: "",
        password: "",
        password2: ""
    });

    const {alertConfig, showNotification} = useAlertNotif();
    const navigate = useNavigate();

    const togglePasswordVisibility = () => {
        setFormData({...formData, showPassword: !formData.showPassword});
    };

    const validateForm = () => {
        let isValid = true;
        const newErrors = {...errors};

        Object.keys(formData).forEach(key => {
            if (!formData[key] && key !== "showPassword" && key !== "role") {
                newErrors[key] = `${key} is required`;
                isValid = false;
            }
        });

        if (formData.password !== formData.password2) {
            newErrors.password2 = "پسورد اول و دوم یکسان نیستند!";
            isValid = false;
        }

        if (!formData.phone_number.match(/^\d{11}$/)) {
            newErrors.phone_number = "شماره تماس نامعتبر";
            isValid = false;
        }

        if (!nationCodeValidator(formData.national_code)) {
            newErrors.national_code = "کد ملی نامعتبر است";
            isValid = false;
        }
        setErrors(newErrors);
        return isValid;
    };

    const handleSignUp = () => {
        if (validateForm()) {
            formData.phone_number = replacePersianNumbers(formData.phone_number);
            formData.national_code = replacePersianNumbers(formData.national_code);
            formData.role = "customer";

            signUp(formData, showNotification).then(() => {
                setTimeout(() => {
                    navigate("/login");
                }, 1000);
            });
        }
    };

    return (
        <Home>
            <AlertNotif alertConfig={alertConfig}/>
            <div
                className="flex w-fit  rounded-2xl gap-0 bg-primary h-[95%] overflow-hidden shadow-2xl shadow-gray-800">
                <img className="flex-1 h-full object-cover hidden lg:block" src="/images/form.png"
                     alt="Background"/>
                <div className="flex-1 w-[50%] flex flex-col justify-between items-center bg-primaryMiddle h-full px-4">
                    <p className="w-full text-center text-2xl font-IRANSansXBold text-black mt-4">ثبت‌نام</p>
                    <div className={"flex flex-col gap-2 w-fit mx-4 "}>
                        <div className={"flex justify-between items-center w-full gap-4"}>
                            <Input
                                label="نام و نام خانوادگی"
                                placeholder="نام کامل خود را وارد کنید"
                                type="text"
                                value={formData.first_name}
                                onChange={(e) => setFormData({...formData, first_name: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold "
                                error={errors.first_name !== ""}
                            />
                            <Input
                                label="شماره تماس"
                                placeholder="09193726908"
                                type="tel"
                                value={formData.phone_number}
                                onChange={(e) => setFormData({...formData, phone_number: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold "
                                error={errors.phone_number !== ""}
                            />
                        </div>

                        <div className={"flex justify-between items-center w-full gap-4"}>
                            {errors.first_name &&
                                <p className="w-full text-red-500 text-sm mt-1">{errors.first_name}</p>}
                            {errors.phone_number &&
                                <p className="w-full text-red-500 text-sm mt-1">{errors.phone_number}</p>}
                        </div>

                        <div className={"flex justify-between items-center w-full gap-4"}>
                            <Input
                                label="ایمیل"
                                placeholder="example@gmail.com"
                                type="email"
                                value={formData.email}
                                onChange={(e) => setFormData({...formData, email: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold"
                                error={errors.email !== ""}
                            />
                            <Input
                                label="نام کاربری"
                                placeholder="example1234"
                                type="text"
                                value={formData.username}
                                onChange={(e) => setFormData({...formData, username: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold"
                                error={errors.username !== ""}
                            />
                        </div>

                        <div className={"flex justify-between items-center w-full gap-4"}>
                            {errors.email && <p className="w-full text-red-500 text-sm">{errors.email}</p>}
                            {errors.username && <p className="w-full text-red-500 text-sm">{errors.username}</p>}
                        </div>

                        <div className={"flex flex-col justify-between items-center w-full gap-4"}>
                            <Input
                                label="کد ملی"
                                placeholder="4409185731"
                                type="tel"
                                value={formData.national_code}
                                onChange={(e) => setFormData({...formData, national_code: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold "
                                error={errors.national_code !== ""}
                            />
                            {errors.national_code &&
                                <p className="w-full text-red-500 text-sm">{errors.national_code}</p>}
                        </div>

                        <div className={"flex justify-between items-center w-full"}>
                            <div className="relative w-full">
                                <Input
                                    label="رمز عبور"
                                    placeholder="رمز عبور خود را وارد کنید"
                                    type={formData.showPassword ? "text" : "password"}
                                    value={formData.password}
                                    onChange={(e) => setFormData({...formData, password: e.target.value})}
                                    color="blue"
                                    variant={"standard"}
                                    className="font-IRANSansXDemiBold"
                                    error={errors.password !== ""}
                                />
                                <button
                                    type="button"
                                    className="absolute right-3 top-1/2 transform -translate-y-1/2 text-primary"
                                    onClick={togglePasswordVisibility}
                                >
                                    {formData.showPassword ? <VisibilityOutlined/> : <VisibilityOffOutlined/>}
                                </button>
                            </div>
                            <Input
                                label="تکرار رمز عبور"
                                placeholder="رمز عبور خود را وارد کنید"
                                type="password"
                                value={formData.password2}
                                onChange={(e) => setFormData({...formData, password2: e.target.value})}
                                color="blue"
                                variant={"standard"}
                                className="font-IRANSansXDemiBold"
                                error={errors.password2 !== ""}
                            />
                        </div>
                        <div className={"flex justify-between items-center w-full gap-4"}>
                            {errors.password && <p className="w-full text-red-500 text-sm mt-1">{errors.password}</p>}
                            {errors.password2 && <p className="w-full text-red-500 text-sm mt-1">{errors.password2}</p>}
                        </div>

                    </div>
                    <div className={"flex flex-col items-center w-full mb-4"}>
                        <Button
                            onClick={handleSignUp}
                            className="font-IRANSansXBold rounded-3xl w-fit px-6 py-2 bg-primary text-white mb-2"
                        >
                            ثبت‌نام
                        </Button>
                        <p className="font-IRANSansXDemiBold w-full text-center mt-2" dir="rtl">
                            حساب کاربری دارید؟
                            <Link to="/login" className="hover:underline">وارد شوید.</Link>
                        </p>
                    </div>
                </div>
            </div>
        </Home>
    );
}

export default SignUp;

// pages/signUp/index.vue
<script setup lang="ts">
import Header from "~/components/Header.vue";
import Footer from "~/components/Footer.vue";
import { ref, computed } from "vue";
import {
  emailRules,
  nameRules,
  passwordRules,
  phoneRules
} from "~/constants/inputRules";
import { password } from "iron-webcrypto";
import ErrorSnackbar from "@/components/ErrorSnackbar.vue";
import { signUp } from "~/pages/signUp/signUp";
import { hashPassword } from "~/utils/hashPassword";
import { replacePersianNumbers } from "~/utils/replacePersianNumbers";
import { nationCodeValidator } from "~/utils/nationalCodeValidator";
import { RoleEnum } from "~/pages/signUp/roles";

const snackbarConfig = ref({
  showError: false,
  errorMessage: "",
  snackType: ""
});

const formData = reactive({
  phone_number: "",
  first_name: "",
  email: "",
  username: "",
  national_code: "",
  password: "",
  password2: "",
  showPassword: false,
  role: "customer"
});


const showPassword = ref(false);

const password2Rules = [
  (v: any) => !!v || "تکرار رمز عبور الزامی است",
  (v: any) => v === formData.password || "رمز عبور و تکرار آن باید یکسان باشند"
];

const nationalCodeRules = [
  (v: any) => !!v || "کد ملی الزامی است",
  (v: any) => nationCodeValidator(v) || "کد ملی معتبر نیست"
];

const togglePasswordVisibility = () => {
  showPassword.value = !showPassword.value;
};

async function handleSignUp() {
  if (formData.password === formData.password2 && formData.email && formData.phone_number) {
    formData.phone_number = replacePersianNumbers(formData.phone_number);
    formData.national_code = replacePersianNumbers(formData.national_code);
    formData.role = RoleEnum[2];

    await signUp(formData, snackbarConfig);
  } else {
  }
}
</script>


<template>
  <div
    class="w-full flex-col gap-24 px-2 lg:px-16 bg-blue-100 pt-8 pb-4"
  >
    <Header />
    <br />
    <div
      class="items-center justify-center flex rounded-2xl"
      style="position: relative"
    >
      <ErrorSnackbar
        class="position-sticky"
        :type="snackbarConfig.snackType"
        v-model="snackbarConfig.showError"
        :errorMessage="snackbarConfig.errorMessage"
      />
      <div
        class=" h-[90%] rounded-2xl flex shadow-2xl shadow-gray-800"
        style="position: absolute"
      >
        <!--        Pattern-->
        <img
          src="public/formPattern.png"
          class="rounded-tl-2xl rounded-bl-2xl h-fill"
        />
        <!--        Form-->
        <div
          class="w-96 bg-primaryLight rounded-2xl flex-col py-4 justify-center align-top px-16 py-8 flex"
        >
          <p
            class="w-full mx-auto text-center font-IRANSansXBold text-3xl mb-4"
          >
            ثبت‌ نام
          </p>
          <v-text-field
            base-color="primary"
            v-model="formData.first_name"
            label="نام و نام خانوادگی"
            placeholder="نام کامل خود را وارد کنید."
            type="text"
            color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="nameRules"
          ></v-text-field>
          <v-text-field
            base-color="primary"
            v-model="formData.phone_number"
            label="شماره تماس"
            placeholder="09193726908"
            type="tel"
            color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="phoneRules"
          ></v-text-field>
          <v-text-field
            v-model="formData.email"
            label="ایمیل"
            placeholder="example@gmail.com"
            type="email"
            color="primary"
            base-color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="emailRules"
          ></v-text-field>
          <v-text-field
            v-model="formData.username"
            label="نام کاربری"
            placeholder="example1234"
            type="text"
            color="primary"
            base-color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="passwordRules"
          ></v-text-field>
          <v-text-field
            v-model="formData.national_code"
            label="کد ملی"
            placeholder="4409185731"
            type="phone_number"
            color="primary"
            base-color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="nationalCodeRules"
          ></v-text-field>
          <v-text-field
            v-model="formData.password"
            label="رمز عبور"
            placeholder="رمز عبور خود را وارد کنید"
            :type="showPassword ? 'text' : 'password'"
            color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :append-icon="showPassword ? 'mdi-eye-off' : 'mdi-eye'"
            @click:append="togglePasswordVisibility"
            :rules="passwordRules"
          ></v-text-field>
          <v-text-field
            v-model="formData.password2"
            label="تکرار رمز عبور"
            placeholder="رمز عبور خود را وارد کنید"
            type="password"
            color="primary"
            class="font-IRANSansXDemiBold"
            hide-details="auto"
            outlined
            :rules="password2Rules"
          ></v-text-field>
          <div class="w-full mx-auto justify-center gap-5 flex">
            <button
              @click="
                () => {
                  handleSignUp();
                }
              "
              class="font-IRANSansXBold rounded-3xl mt-2 w-fit px-6 py-2 bg-primary"
            >
              ثبت‌نام
            </button>
          </div>

          <p class="font-IRANSansXDemiBold w-full mt-4 text-center" dir="rtl">
            حساب کاربری دارید؟
            <NuxtLink to="/signIn"
            ><u class="hover:cursor-pointer">وارد شوید.</u></NuxtLink
            >
          </p>
        </div>
      </div>
      <img src="public/comingsoon.png" class="rounded-2xl h-3/5" />
    </div>

    <br />
    <Footer />
  </div>
</template>
