// src/components/Landing/Header.tsx
import React from "react";
import {ShoppingCartOutlined} from "@mui/icons-material";
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined';
import {Link} from "react-router-dom";

function Header() {
    return (
        <div className={"flex justify-between h-16 bg-white rounded-2xl px-4"}>
            <div className={"flex flex-1 items-center gap-2 "}>
                <ShoppingCartOutlined fontSize={"large"} className="text-primary"/>
                <Link to="/signIn" className={" gap-2 flex items-center"}>
                    <AccountCircleOutlinedIcon fontSize={"large"} className="text-primary"/>
                    <p className={"font-IRANSansXBold text-primary"}>
                        ورود/ثبت نام
                    </p>
                </Link>
            </div>
            <div className={"flex flex-1 justify-center items-center "}>
                <img src={"./images/logo.png"} className={"h-full"}/>
            </div>
            <div className={"flex flex-1  justify-end items-center"}>
                <Link to="/shop" className={" gap-2 flex items-center"}>
                    <p className={"font-IRANSansXBold text-primary"}>
                        بسته‌ها
                    </p>
                </Link>
            </div>
        </div>
    );
}

export default Header;

// components/Header.vue
<script setup lang="ts">
const goToHome = () => {
  const router = useRouter()
  router.push("/")
};
</script>

<template>
  <div
    class="flex justify-space-between items-center h-20 rounded-3xl bg-white px-4 shadow-gray-100 shadow-2xl"
  >
    <div class="flex flex-1 justify-start items-center h-full">
      <v-btn
        prepend-icon="mdi-cart-outline"
        variant="plain"
        v-ripple="false"
        color="primary"
        active-color="white"
        size="large"
        to="/shop"
        class="font-IRANSansXBold tracking-normal"
      >فروشگاه
      </v-btn>
      <v-btn
        prepend-icon="mdi-account-circle-outline"
        variant="plain"
        v-ripple="false"
        color="primary"
        size="large"
        to="/signIn"
        class="font-IRANSansXBold tracking-normal"
      >ورود/ثبت‌نام
      </v-btn>
    </div>

    <div class="flex flex-1 justify-center items-center h-full">
      <NuxtLink to="/" class="h-full">
        <img src="public/logo/mainLogo.svg" class="h-full" @click="goToHome" />
      </NuxtLink>
    </div>

    <div class="flex flex-1 justify-end items-center">
      <v-btn
        variant="plain"
        color="primary"
        size="large"
        v-ripple="false"
        to="/shop"
        class="font-IRANSansXDemiBold"
      >
        بسته‌ها
      </v-btn>
      <v-btn
        variant="plain"
        color="primary"
        size="large"
        v-ripple="false"
        to="/shop"
        class="font-IRANSansXDemiBold"
      >
        طرح‌ها
      </v-btn>
    </div>
  </div>
</template>

<style scoped></style>
